---
title: "CAISO GhG Emissions"
author: "Christopher Hull"
date: "5/8/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read in data
```{r}
library(reshape)
library(tidyverse)
#library(datetime)
#library(chron)

# wd <- "C:/Users/liusa/github/MSE243"
# 
# combining <- function(pattern) {
#   files <- list.files(pattern = pattern)
#   for (f in files) {
#     datum <- read.csv(f)
#     header <- colnames(datum)[1]
#     datum <- 
#       datum %>% 
#       dplyr::rename("Date" = header)
#     datum["Date"][1] <- substring(header,2)
#     write.csv(datum,f,row.names = F)
#   }
#   return(do.call(rbind, lapply(files,read.csv)))
# }
# 
# setwd(paste0(wd,"/2019_ghg"))
# 
# caiso_2019 <- 
#   combining("CAISO-co2-2019[0-9][0-9][0-9][0-9].csv")
# 
# setwd(paste0(wd,"/2020_ghg"))
# 
# caiso_2020 <-
#   combining("CAISO-co2-20200[0-9][0-9][0-9].csv")
# 
# setwd(wd)
# 
# write.csv(caiso_2019,"caiso_2019.csv",row.names=F)
# write.csv(caiso_2020,"caiso_2020.csv",row.names=F)

caiso_2019 <- read.csv("caiso_2019.csv")
caiso_2020 <- read.csv("caiso_2020.csv")

```

Reshape, clean and condense into hourly 
```{r}
data_2019 <- melt(caiso_2019, id = c("Date"))
data_2019 <- data_2019 %>%
  dplyr::rename(time = variable,
         "CO2" = value) %>% #example name
  mutate(time = substring(time,2,3)) %>%
  group_by(Date,time) %>%
  summarise("CO2_sum"= sum(CO2)) #condense into hourly

data_2020 <- melt(caiso_2020, id = c("Date"))
data_2020 <- data_2020 %>%
  dplyr::rename(time = variable,
         "CO2" = value) %>% #example name
  mutate(time = substring(time,2,3)) %>%
  group_by(Date,time) %>%
  summarise("CO2_sum"= sum(CO2)) #condense into hourly
```


Plot data
```{r}
ggplot(tail(data_2019,240)) + 
  geom_line(aes(x = time, y = CO2_sum, color=Date , group=Date))
ggplot(tail(data_2020,240)) + 
  geom_line(aes(x = time, y = CO2_sum, color=Date , group=Date))
```


Analysis of diff b/t 2020 and 2019
```{r}
library(lubridate)
combined_data = cbind(data_2019, data_2020)  %>%
  select(-c(Date1, time1)) %>%
  ungroup(Date)%>%
  mutate(CO2_diff = CO2_sum1 - CO2_sum, 
         CO2_diff = replace_na(CO2_diff, 0),
         Date = mdy(Date),
         time = as.numeric(time))
         #CO2_diff = 2020 - 2019  
  
diff_by_day = combined_data %>%
  group_by(Date) %>%
  summarise("CO2_diff_by_day" = sum(CO2_diff))

diff_by_hour = combined_data %>% 
  group_by(time) %>% 
  summarise("CO2_diff_by_hour" = mean(CO2_diff)) 



```

```{r}
summary(combined_data$CO2_diff) # mostly > 0
```




Graphing 
```{r}
ggplot(combined_data) + 
  geom_line(aes(x = time, y = CO2_diff, color=Date , group=Date)) + #all dates
  geom_hline(yintercept = 0, linetype = "dashed", color = "red", size = 1) +
  ggtitle("Differences by Time (2020 minus 2019), Mar 1 - May 7") +
  ylab("Difference in CO2 emissions") 
ggsave("diff_by_hour_all_days.PNG")

ggplot(head(combined_data,360)) + 
  geom_line(aes(x = time, y = CO2_diff, color=Date , group=Date)) + #first 15
  geom_hline(yintercept = 0, linetype = "dashed", color = "red", size = 1) +
  ggtitle("Differences by Time (2020 minus 2019), Mar 1 - Mar 15") +
  ylab("Difference in CO2 emissions") 
ggsave("diff_by_hour_first_15_days.PNG")

ggplot(tail(combined_data,360)) + 
  geom_line(aes(x = time, y = CO2_diff, color=Date , group=Date)) + #final 15
  geom_hline(yintercept = 0, linetype = "dashed", color = "red", size = 1) +
  ggtitle("Differences by Time (2020 minus 2019), Apr 23 - May 7") +
  ylab("Difference in CO2 emissions") 
ggsave("diff_by_hour_final_15_days.PNG")

```
Differences by day and by hour

```{r}
ggplot(diff_by_day) +
  geom_point(aes(x = Date, y = CO2_diff_by_day)) +
  geom_smooth(aes(x = Date, y = CO2_diff_by_day)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red", size = 1) +
  ylab("Difference in CO2 emissions") +
  ggtitle("Differences in CO2 emissions by day (2020 minus 2019)")
ggsave("diff_by_day.png")

ggplot(diff_by_hour) +
  geom_point(aes(x = time, y = CO2_diff_by_hour)) +
  geom_smooth(aes(x = time, y = CO2_diff_by_hour)) + #for some reason the geom_smooth is not showing up for me?
  geom_hline(yintercept = 0, linetype = "dashed", color = "red", size = 1) +
  ylab("Difference in CO2 emissions") +
  ggtitle("Avg differences in CO2 emissions by hour (2020 minus 2019)")
ggsave("diff_by_hour.png")

```


